name: Test Deployment Protection

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Fake Deploy Job
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate deployment
        run: |
          echo "Starting fake deployment..."
          sleep 10
          echo "Deployment step complete (waiting for approval to continue)"
