name: Test Deployment Protection

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Type anything here to test workflow inputs"
        required: true
        default: "hello-world"

jobs:
  preflight:
    name: Preflight (show inputs)
    runs-on: ubuntu-latest
    steps:
      - name: Show deployment details in logs
        run: |
          echo "🔹 Triggered by: $GITHUB_ACTOR"
          echo "🔹 Input test_input: ${{ inputs.test_input }}"
          echo "🔹 Commit SHA: $GITHUB_SHA"
          echo "🔹 Repo: $GITHUB_REPOSITORY"

      - name: Write inputs to job summary
        run: |
          {
            echo "## 🚦 Deployment Preflight";
            echo "";
            echo "- **Triggered by:** $GITHUB_ACTOR";
            echo "- **Input \`test_input\`:** \`${{ inputs.test_input }}\`";
            echo "- **Commit SHA:** \`$GITHUB_SHA\`";
            echo "- **Repo:** \`$GITHUB_REPOSITORY\`";
          } >> "$GITHUB_STEP_SUMMARY"

  deploy:
    name: Fake Deploy Job
    runs-on: ubuntu-latest
    needs: preflight
    # 👇 Environment gate happens here, after you can view preflight output
    environment:
      name: production
    steps:
      - name: Simulate deployment
        run: |
          echo "Starting fake deployment..."
          sleep 5
          echo "Deployment finished successfully for input: '${{ inputs.test_input }}'"
