name: Test Deployment Protection

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Type anything here to test workflow inputs"
        required: true
        default: "hello-world"

jobs:
  deploy:
    name: Fake Deploy Job
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Print the input
        run: |
          echo "User entered: ${{ inputs.test_input }}"

      - name: Simulate deployment
        run: |
          echo "Starting fake deployment..."
          sleep 5
          echo "Deployment finished successfully for input: '${{ inputs.test_input }}'"
